import Layout from "@/components/Layout";
import SEOHead from "@/components/SEOHead";
import CgpaToPercentageCalc from "@/components/calculators/CgpaToPercentage";

const CgpaToPercentagePage = () => (
  <Layout>
    <SEOHead
      title="CGPA to Percentage Converter — CGPA Calculator"
      description="Convert CGPA to percentage instantly with our free CGPA Calculator. Supports both 10-point and 4-point grading scales. Accurate formula: CGPA × 9.5 = Percentage."
      canonical="https://cgpa-percentage.github.io/cgpa-to-percentage"
      jsonLd={{
        "@context": "https://schema.org",
        "@type": "WebApplication",
        "name": "CGPA to Percentage Converter",
        "url": "https://cgpa-percentage.github.io/cgpa-to-percentage",
        "description": "Free online CGPA to percentage converter supporting 10-point and 4-point scales.",
        "applicationCategory": "EducationalApplication",
        "operatingSystem": "All",
        "offers": { "@type": "Offer", "price": "0", "priceCurrency": "USD" },
        "aggregateRating": { "@type": "AggregateRating", "ratingValue": "4.8", "ratingCount": "47", "bestRating": "5", "worstRating": "1" }
      }}
    />
    <nav aria-label="Breadcrumb" className="text-sm text-muted-foreground mb-6">
      <a href="/" className="hover:text-primary">Home</a> <span className="mx-2">/</span> <span className="text-foreground">CGPA to Percentage</span>
    </nav>
    <h1 className="text-4xl font-extrabold tracking-tight text-foreground mb-2">CGPA to Percentage Converter</h1>
    <p className="text-muted-foreground mb-8">Use our free CGPA Calculator to convert your CGPA to percentage on 10-point or 4-point scales.</p>
    <CgpaToPercentageCalc />
    <article className="glass-panel p-8 md:p-12 mt-12">
      <h2 className="text-2xl font-bold text-foreground mb-4">How to Convert CGPA to Percentage Using Our CGPA Calculator</h2>
      <div className="space-y-4 text-muted-foreground text-sm leading-relaxed">
        <p>Converting CGPA to percentage is one of the most common academic calculations. Our <strong className="text-foreground">CGPA Calculator</strong> makes this conversion instant and accurate for both 10-point and 4-point grading scales.</p>
        <h3 className="text-lg font-semibold text-foreground">CGPA to Percentage Formula (10-Point Scale)</h3>
        <p>The standard formula used by our CGPA Calculator and approved by UGC: <strong className="text-foreground">Percentage = CGPA × 9.5</strong>. Example: 8.2 CGPA × 9.5 = 77.9%.</p>
        <h3 className="text-lg font-semibold text-foreground">CGPA to Percentage Formula (4-Point Scale)</h3>
        <p>For 4.0 GPA scale: <strong className="text-foreground">Percentage = (CGPA / 4.0) × 100</strong>. A 3.5 CGPA = 87.5%.</p>
        <h3 className="text-lg font-semibold text-foreground">When Do You Need the CGPA Calculator for This Conversion?</h3>
        <ul className="list-disc list-inside space-y-1 ml-2">
          <li>University applications requiring percentage scores</li>
          <li>Job applications with minimum percentage criteria</li>
          <li>Scholarship applications</li>
          <li>Comparing academic performance across grading systems</li>
        </ul>
        <h3 className="text-lg font-semibold text-foreground">CGPA to Percentage Conversion Table</h3>
        <p>Here's a quick reference generated by our CGPA Calculator for the 10-point scale:</p>
        <div className="grid grid-cols-2 gap-2 max-w-xs mt-2">
          {[6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10].map(c => (
            <div key={c} className="contents">
              <span className="px-3 py-1.5 bg-muted/50 rounded text-foreground font-medium">{c} CGPA</span>
              <span className="px-3 py-1.5 bg-muted/50 rounded">{(c * 9.5).toFixed(1)}%</span>
            </div>
          ))}
        </div>
      </div>
    </article>
  </Layout>
);

export default CgpaToPercentagePage;
